// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFlU6fEnEBJXX-yPTVHf0huDsc9n6vBM',
    appId: '1:19012932592:web:fae1ae406af75fa0a3c335',
    messagingSenderId: '19012932592',
    projectId: 'ultrachatri',
    authDomain: 'ultrachatri.firebaseapp.com',
    databaseURL: 'https://ultrachatri-default-rtdb.firebaseio.com',
    storageBucket: 'ultrachatri.appspot.com',
    measurementId: 'G-GJR361C26R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-_n2ELYfBC9Rdgz-wzqoBGcMtjJLbcU',
    appId: '1:19012932592:android:ea6d03237441620ca3c335',
    messagingSenderId: '19012932592',
    projectId: 'ultrachatri',
    databaseURL: 'https://ultrachatri-default-rtdb.firebaseio.com',
    storageBucket: 'ultrachatri.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9h75w0C-ZX3G5M2OIc_TBMaJXw2Pz3sQ',
    appId: '1:19012932592:ios:9e9a47374986f733a3c335',
    messagingSenderId: '19012932592',
    projectId: 'ultrachatri',
    databaseURL: 'https://ultrachatri-default-rtdb.firebaseio.com',
    storageBucket: 'ultrachatri.appspot.com',
    iosClientId: '19012932592-j7uqmfpdpn74o7294h104ms08ennp4is.apps.googleusercontent.com',
    iosBundleId: 'com.example.ultaChatri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9h75w0C-ZX3G5M2OIc_TBMaJXw2Pz3sQ',
    appId: '1:19012932592:ios:9e9a47374986f733a3c335',
    messagingSenderId: '19012932592',
    projectId: 'ultrachatri',
    databaseURL: 'https://ultrachatri-default-rtdb.firebaseio.com',
    storageBucket: 'ultrachatri.appspot.com',
    iosClientId: '19012932592-j7uqmfpdpn74o7294h104ms08ennp4is.apps.googleusercontent.com',
    iosBundleId: 'com.example.ultaChatri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGFlU6fEnEBJXX-yPTVHf0huDsc9n6vBM',
    appId: '1:19012932592:web:2c66cda520321039a3c335',
    messagingSenderId: '19012932592',
    projectId: 'ultrachatri',
    authDomain: 'ultrachatri.firebaseapp.com',
    databaseURL: 'https://ultrachatri-default-rtdb.firebaseio.com',
    storageBucket: 'ultrachatri.appspot.com',
    measurementId: 'G-1XPRJHFM2W',
  );
}
